// This file is autogenerated by CMake: DO NOT EDIT

#include "loggingcategory.h"


#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(KArchiveLog, "kf5.karchive", QtWarningMsg)
#else
Q_LOGGING_CATEGORY(KArchiveLog, "kf5.karchive")
#endif

